# Services
services:

  # Nginx Service
  dclm-events-app:
    container_name: dclm-events-app
    image: richarvey/nginx-php-fpm:1.9.1
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      WEBROOT: ${WEBROOT}
    ports:
      - 1002:80
    networks:
      - dclm-events-app
    volumes:
      - ./.docker/events.conf:/etc/nginx/sites-available/default.conf
    restart: always

networks:
  dclm_events:
    name: dclm-events-app