# Services
services:

  # Nginx Service
  events:
    container_name: events.dclm.org
    image: wyveo/nginx-php-fpm:php74
    working_dir: /var/www/events
    ports:
      - 1001:80
    volumes:
      - .:/var/www/events
      - ./.docker/nginx/events.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/php8.1/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php8.1/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always