# Services
services:

  # Nginx Service
  events:
    container_name: events.dclm.org
    # build:
    #   context: ./.docker
    #   args:
    #     HOST_UID: $HOST_UID
    image: opeoniye/nginx-php:7.4
    working_dir: /var/www/events
    ports:
      - 1002:80
    volumes:
      - .:/var/www/events
      - ./.docker/events.conf:/etc/nginx/sites-available/default.conf
      - ./.docker/php8.1/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php8.1/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always