# Services
services:

  events-app:
    container_name: events-app
    image: richarvey/nginx-php-fpm:1.9.1  # contains php 7.4.10 used for this project
    # environment:
      # GIT_REPO: ${GIT_REPO}
      # GIT_EMAIL: ${GIT_EMAIL}
      # GIT_NAME: ${GIT_NAME}
      # GIT_BRANCH: ${GIT_BRANCH}
      # GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      # WEBROOT: ${WEBROOT}
    ports:
      - 1002:80
    networks:
      - bams
    volumes:
      - ./:/var/www/html
      # - ./.env:/var/www/html/.env
      - ./.docker/events.conf:/etc/nginx/sites-available/default.conf
    restart: always

networks:
  bams:
    name: bams-dev
    external: true